package com.example.tasker.ui.view_model

import androidx.lifecycle.ViewModel

class MainViewModel: ViewModel() {
    private val bearer_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJqd3QtYXVkaWVuY2UiLCJpc3MiOiJ5b3VyLWRvbWFpbi5jb20iLCJ1c2VySWQiOiJjN2VmM2YzYS1mYjYxLTQxMzEtYmI0My1mNjk0YTZlZWU0NzAiLCJleHAiOjE3MTU5NzE2ODB9.ZgOybuoeFh0y2Gp75lB3LQHq9l_6y0zyY8Gz3uCn4FM"

}